# Generated by Django 5.1.4 on 2024-12-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('product', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=10)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=10)),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('high', models.DecimalField(decimal_places=10, max_digits=10)),
                ('low', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
