# Generated by Django 5.1.4 on 2024-12-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstats',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productstats',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productstats',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productstats',
            name='product',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productstats',
            name='volume',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
