# Generated by Django 5.1.4 on 2024-12-08 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productstats_high_alter_productstats_low_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstats',
            old_name='price',
            new_name='last',
        ),
    ]
